[package]
name = "chapter-14"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
art-example-cekingx = { path = './art' }

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3
